# ============================================================================
# AUTO-GENERATED by worlds/mm_2ship/tools/genlogic. DO NOT EDIT BY HAND.
# Regenerate with:
#   python worlds/mm_2ship/tools/genlogic/generate.py /path/to/2ship2harkinian
# ============================================================================

"""Provenance of the generated data: the 2ship checkout it came from."""

# 2ship's CMake project version, which the client reports as gBuildVersion.
BUILD_VERSION: str = '0.10.0'

SOURCE_COMMIT: str = '969e4f7f1894755139d10314ac94d825777146e1'

# True when that checkout had uncommitted changes, so the commit alone
# does not identify the sources this was built from.
SOURCE_DIRTY: bool = False
